### ISSUE TITLE
can these be removed?

### ISSUE THREAD

**Issue by shubham399** [rahuljain5/impulse2k18#10]
<script id="twitter-wjs" src="i/widgets.js"></script>
<script id="facebook-jssdk" src="i/sdk.js"></script>
<script async="" src="i/analytics.js"></script>
<script type="text/javascript" src="i/app-11f510ab04.js"></script>

https://github.com/rahuljain5/impulse2k18/blob/62a16138d79f8c44fe43f359fdd4b60427e61f49/contactus.html#L124

**Comment by rahuljain5** [comment]
Removed.
